In [ ]:
#TASK_01
class Patient:
  def __init__(self,name,age,weight,height):
    self.name = name
    self.age = age
    self.weight = weight
    self.height = height
    self.bmi = weight/(height/100)**2
  def printDetails(self):
    print('Name:',self.name)
    print('Age:',self.age)
    print('Weight:',self.weight,'Kg')
    print('Height', self.height, 'cm')
    print('BMI:',self.bmi)
p1 = Patient("A", 55, 63.0, 158.0)
p1.printDetails()
print("====================")
p2 = Patient("B", 53, 61.0, 149.0)
p2.printDetails()

Name: A
Age: 55
Weight: 63.0 Kg
Height 158.0 cm
BMI: 25.236340330075304
====================
Name: B
Age: 53
Weight: 61.0 Kg
Height 149.0 cm
BMI: 27.476239809017613

In [ ]:
#TASK_02
class Shape:
  def __init__(self, name, base, height):
    self.name = name
    self.base = base
    self.height = height
  def area(self):
    triangle = .5* self.base * self.height
    rhombus = .5 * self.base * self.height
    square = self.base * self.height
    rectangle =  self.base * self.height
    if self.name == "Triangle":
      print("Area: ",triangle)
    elif self.name == "Square":
      print("Area: ",square)
    elif self.name == "Rhombus":
      print("Area: ",rhombus)
    elif self.name == "Rectangle":
      print("Area: ", rectangle)
    else:
      print("Area: Shape unknown")

triangle = Shape("Triangle",10,25)
triangle.area()
print("==========================")
square = Shape("Square",10,10)
square.area()
print("==========================")
rhombus = Shape("Rhombus",18,25)
rhombus.area()
print("==========================")
rectangle = Shape("Rectangle",15,30)
rectangle.area()
print("==========================")
trapezium = Shape("Trapezium",15,30)
trapezium.area()

Area:  125.0
==========================
Area:  100
==========================
Area:  225.0
==========================
Area:  450
==========================
Area: Shape unknown

In [ ]:
#Task_3
class Calculator:
  def __init__(self):
    print("Calculator is ready!")
  def calculate(self, val1, val2, oprt):
    self.val1 = val1
    self.val2 = val2
    self.oprt = oprt
    if self.oprt == "+":
      return_value = self.val1 + self.val2
    elif self.oprt == "-":
      return_value = val - self.val2
    elif self.oprt == "*":
      return_value = val * self.val2
    elif self.oprt == "/":
      return_value = val / self.val2
    return return_value

  def showCalculation(self):
    print(f"{self.val1} {self.oprt} {self.val2} = {val}")
c1 = Calculator()
print("==================")
val = c1.calculate(10, 20, '+')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 10, '-')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 5, '*')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 16, '/')
print("Returned value:", val)
c1.showCalculation()

Calculator is ready!
==================
Returned value: 30
10 + 20 = 30
==================
Returned value: 20
30 - 10 = 20
==================
Returned value: 100
20 * 5 = 100
==================
Returned value: 6.25
100 / 16 = 6.25

In [ ]:
#Task_4
class Programmer:
  def __init__(self, name, lang, exp):
    self.name = name
    self.lang = lang
    self.exp = exp
    print("Horray! A new programmer is born")
  def printDetails(self):
    print(f"Name: {self.name}\nLanguage: {self.lang}\nExperience: {self.exp}")
  def addExp(self,expr):
    print("Updating experience of Jon Snow")
    self.exp += expr


p1 = Programmer("Ethen Hunt", "Java", 10)
p1.printDetails()
print('--------------------------')
p2 = Programmer("James Bond", "C++", 7)
p2.printDetails()
print('--------------------------')
p3 = Programmer("Jon Snow", "Python", 4)
p3.printDetails()
p3.addExp(5)
p3.printDetails()

Horray! A new programmer is born
Name: Ethen Hunt
Language: Java
Experience: 10
--------------------------
Horray! A new programmer is born
Name: James Bond
Language: C++
Experience: 7
--------------------------
Horray! A new programmer is born
Name: Jon Snow
Language: Python
Experience: 4
Updating experience of Jon Snow
Name: Jon Snow
Language: Python
Experience: 9

In [ ]:
print(13**7%372)

301

In [ ]:
#Task_05
class UberEats:
  def __init__(self, name, num, loc):
    self.name = name
    self.num = num
    self.loc = loc
    print(f"{self.name}, welcome to UberEats!")
  def add_items(self, food, drinks, price1, price2):
    self.dict1 = {}
    self.dict1[food] = price1
    self.dict1[drinks] = price2
    self.total_price = price1+price2

  def print_order_detail(self):
    print(f"User details: Name: {self.name}, Phone: {self.num}, Address: {self.loc}")
    print(f"Orders: {self.dict1}")
    return f"Total Paid Amount: {self.total_price}"



order1 = UberEats("Shakib", "01719658xxx", "Mohakhali")
print("=========================")
order1.add_items("Burger", "Coca Cola", 220, 50)
print("=========================")
print(order1.print_order_detail())
print("=========================")
order2 = UberEats ("Siam", "01719659xxx", "Uttara")
print("=========================")
order2.add_items("Pineapple", "Dairy Milk", 80, 70)
print("=========================")
print(order2.print_order_detail())

Shakib, welcome to UberEats!
=========================
=========================
User details: Name: Shakib, Phone: 01719658xxx, Address: Mohakhali
Orders: {'Burger': 220, 'Coca Cola': 50}
Total Paid Amount: 270
=========================
Siam, welcome to UberEats!
=========================
=========================
User details: Name: Siam, Phone: 01719659xxx, Address: Uttara
Orders: {'Pineapple': 80, 'Dairy Milk': 70}
Total Paid Amount: 150

In [ ]:
#Task_06
class Customer:
  def __init__(self, name):
    self.name = name
  def greet(self, *greet):
    if len(greet)!=0:
        print("Hello "+ greet[0] + "!")
    else:
        print("Hello!")
  def purchase(self, *items):
    print(f"{self.name}, you purchased {len(items)} item(s):")
    print(*items, sep="\n")


customer_1 = Customer("Sam")
customer_1.greet()
customer_1.purchase("chips", "chocolate", "orange juice")
print("-----------------------------")
customer_2 = Customer("David")
customer_2.greet("David")
customer_2.purchase("orange juice")

Hello!
Sam, you purchased 3 item(s):
chips
chocolate
orange juice
-----------------------------
Hello David!
David, you purchased 1 item(s):
orange juice

In [ ]:
#Task_07
class Cat:

    def __init__(self,colour = "White", action = "sitting"):
        if colour != None and action != None:
            self.colour = colour
            self.action = action
        elif colour != None:
            self.colour = colour
    def printCat(self):
         print ("{} cat is {}".format(self.colour,self.action))
    def changeColor(self,color):
        self.colour = color
c1 = Cat()
c2 = Cat("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()

White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Blue cat is sitting
Purple cat is jumping

In [ ]:
#Task_8

class Student :

    def __init__ (self, name, id, dept = None):
        if dept != None:
            self.name = name
            self.id = id
            self.dept = dept
            print ("Name:",self.name)
            print ("ID:",self.id)
            print ("Department:",self.dept)
        else:
            self.name = name
            self.id = id
            self.dept = dept
            print ("Name:",self.name)
            print ("ID:",self.id)
            print ("Department: CSE")

    def dailyEffort (self,hour):
        print ("Daily Effort:",hour,"hour(s)")
        if hour <= 2:
            print ("Suggestion: Should give more effort!")
        elif hour <= 4:
            print ("Suggestion: Keep up the good work!")
        else:
            print ("Suggestion: Excellent! Now motivate others.")

    def printDetails(self):
        pass

harry = Student('Harry Potter', 123)
harry.dailyEffort(3)
harry.printDetails()
print('========================')
john = Student("John Wick", 456, "BBA")
john.dailyEffort(2)
john.printDetails()
print('========================')
naruto = Student("Naruto Uzumaki", 777, "Ninja")
naruto.dailyEffort(6)
naruto.printDetails()

Name: Harry Potter
ID: 123
Department: CSE
Daily Effort: 3 hour(s)
Suggestion: Keep up the good work!
========================
Name: John Wick
ID: 456
Department: BBA
Daily Effort: 2 hour(s)
Suggestion: Should give more effort!
========================
Name: Naruto Uzumaki
ID: 777
Department: Ninja
Daily Effort: 6 hour(s)
Suggestion: Excellent! Now motivate others.

In [ ]:
#Task_09
class Batsman:

    def __init__(self,*info):
        if len(info) == 3:
            self.name = info[0]
            self.runs_scored = info[1]
            self.balls_faced = info[2]
        else:
            self.name = "New Batsman"
            self.runs_scored = info[0]
            self.balls_faced = info[1]

    def printCareerStatistics(self):
        print ("Name:",self.name)
        print ("Runs Scored:",self.runs_scored,", Balls Faced:",self.balls_faced)


    def battingStrikeRate(self):
        sr = (self.runs_scored / self.balls_faced) * 100
        return sr

    def setName(self,setname):
        self.name = setname

b1 = Batsman(6101, 7380)
b1.printCareerStatistics()
print("============================")
b2 = Batsman("Liton Das", 678, 773)
b2.printCareerStatistics()
print("----------------------------")
print(b2.battingStrikeRate())
print("============================")
b1.setName("Shakib Al Hasan")
b1.printCareerStatistics()
print("----------------------------")
print(b1.battingStrikeRate())

Name: New Batsman
Runs Scored: 6101 , Balls Faced: 7380
============================
Name: Liton Das
Runs Scored: 678 , Balls Faced: 773
----------------------------
87.71021992238033
============================
Name: Shakib Al Hasan
Runs Scored: 6101 , Balls Faced: 7380
----------------------------
82.66937669376694

In [ ]:
#TASK_10
class Author:

    def __init__ (self, name = "Default",*books):
        self.name = name
        self.books = books

    def addBooks (self,*books):
        self.books = books

    def printDetails(self):
        print("Author Name:",self.name)
        print("--------")
        print("List of Books:")
        print(*self.books,sep='\n')

    def changeName(self,changename):
        self.name = changename

auth1 = Author('Humayun Ahmed')
auth1.addBooks('Deyal', 'Megher Opor Bari')
auth1.printDetails()
print("===================")
auth2 = Author()
print(auth2.name)
auth2.changeName('Mario Puzo')
auth2.addBooks('The Godfather', 'Omerta', 'The Sicilian')
print("===================")
auth2.printDetails()
print("===================")
auth3 = Author('Paolo Coelho', 'The Alchemist', 'The Fifth Mountain')
auth3.printDetails()

Author Name: Humayun Ahmed
--------
List of Books:
Deyal
Megher Opor Bari
===================
Default
===================
Author Name: Mario Puzo
--------
List of Books:
The Godfather
Omerta
The Sicilian
===================
Author Name: Paolo Coelho
--------
List of Books:
The Alchemist
The Fifth Mountain

In [ ]:
#TASK_11
class TaxiLagbe:
  def __init__(self,taxi,area):
    self.taxi=taxi
    self.area=area
    self.list1=[]
    self.list2=[]
  def addPassenger(self,*val):
    for item in val:
      name,fare=item.split('_')
      if len(self.list1)<4:
        self.list1.append(name)
        self.list2.append(fare)
        print('Dear '+name+'! Welcome to TaxiLagbe.')
      else:
        print('Taxi Full! No more passengers can be added.')
  def printDetails(self):
    self.total=0
    print('Trip info for Taxi number:',self.taxi)
    print('This taxi can cover only',self.area,'area.')
    print('Total passengers:',len(self.list1))
    print('Passenger lists:')
    for item2 in self.list1:
      if item2==self.list1[len(self.list1)-1]:
        print(item2)
      else:
        print(item2,end=', ')
    for item3 in self.list2:
      self.total+=int(item3)
    print(f"Total collected fare: {self.total} Taka")

taxi1 = TaxiLagbe('1010-01', 'Dhaka')
print('-------------------------------')
taxi1.addPassenger('Walker_100', 'Wood_200')
taxi1.addPassenger('Matt_100')
taxi1.addPassenger('Wilson_105')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi1.addPassenger('Karen_200')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi2 = TaxiLagbe('1010-02', 'Khulna')
taxi2.addPassenger('Ronald_115')
taxi2.addPassenger('Parker_215')
print('-------------------------------')
taxi2.printDetails()

-------------------------------
Dear Walker! Welcome to TaxiLagbe.
Dear Wood! Welcome to TaxiLagbe.
Dear Matt! Welcome to TaxiLagbe.
Dear Wilson! Welcome to TaxiLagbe.
-------------------------------
Trip info for Taxi number: 1010-01
This taxi can cover only Dhaka area.
Total passengers: 4
Passenger lists:
Walker, Wood, Matt, Wilson
Total collected fare: 505 Taka
-------------------------------
Taxi Full! No more passengers can be added.
-------------------------------
Trip info for Taxi number: 1010-01
This taxi can cover only Dhaka area.
Total passengers: 4
Passenger lists:
Walker, Wood, Matt, Wilson
Total collected fare: 505 Taka
-------------------------------
Dear Ronald! Welcome to TaxiLagbe.
Dear Parker! Welcome to TaxiLagbe.
-------------------------------
Trip info for Taxi number: 1010-02
This taxi can cover only Khulna area.
Total passengers: 2
Passenger lists:
Ronald, Parker
Total collected fare: 330 Taka

In [ ]:
#TASK_12
class Account:

    def __init__ (self, name = "Default Account", balance = 0.0):
        self.name = name
        self.balance = balance

    def details(self):
        return f"{self.name}\n{self.balance}"

    def withdraw(self,withdraw):
        self.balance =self.balance - withdraw
        if self.balance <= 3070.0:
          self.balance += withdraw
          print("Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.")
        else:
          print("Withdraw successful! New balance is:", self.balance)

a1 = Account()
print(a1.details())
print("------------------------")
a1.name = "Oliver"
a1.balance = 10000.0
print(a1.details())
print("------------------------")
a2 = Account("Liam")
print(a2.details())
print("------------------------")
a3 = Account("Noah",400)
print(a3.details())
print("------------------------")
a1.withdraw(6930)
print("------------------------")
a2.withdraw(600)
print("------------------------")
a1.withdraw(6929)

Default Account
0.0
------------------------
Oliver
10000.0
------------------------
Liam
0.0
------------------------
Noah
400
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Withdraw successful! New balance is: 3071.0

In [ ]:
#Task_13
class StudentDatabase:
  def __init__(self,name,id):
    self.name=name
    self.id=id
    self.grades={}
  def calculateGPA(self,result,semester):
    list1=[]
    list2=[]
    for item1 in result:
      sub,cg=item1.split(': ')
      list1.append(sub)
      list2.append(cg)
    list1=tuple(list1)
    total=0
    for item2 in list2:
      total+=float(item2)
    cgpa=total/len(list2)
    self.grades[semester]={list1:cgpa}
  def printDetails(self):
    print('Name:',self.name)
    print('ID:',self.id)
    for var1,var2 in self.grades.items():
      print('Course taken in',var1+':')
      for var3,var4 in var2.items():
        for item1 in var3:
          print(item1)
        print('GPA:',var4)
s1 = StudentDatabase('Pietro', '10101222')
s1.calculateGPA(['CSE230: 4.0', 'CSE220: 4.0', 'MAT110: 4.0'], 'Summer2020')
s1.calculateGPA(['CSE250: 3.7', 'CSE330: 4.0'], 'Summer2021')
print(f'Grades for {s1.name}\n{s1.grades}')
print('------------------------------------------------------')
s1.printDetails()
s2 = StudentDatabase('Wanda', '10103332')
s2.calculateGPA(['CSE111: 3.7', 'CSE260: 3.7', 'ENG101: 4.0'], 'Summer2022')
print('------------------------------------------------------')
print(f'Grades for {s2.name}\n{s2.grades}')
print('------------------------------------------------------')
s2.printDetails()

Grades for Pietro
{'Summer2020': {('CSE230', 'CSE220', 'MAT110'): 4.0}, 'Summer2021': {('CSE250', 'CSE330'): 3.85}}
------------------------------------------------------
Name: Pietro
ID: 10101222
Course taken in Summer2020:
CSE230
CSE220
MAT110
GPA: 4.0
Course taken in Summer2021:
CSE250
CSE330
GPA: 3.85
------------------------------------------------------
Grades for Wanda
{'Summer2022': {('CSE111', 'CSE260', 'ENG101'): 3.8000000000000003}}
------------------------------------------------------
Name: Wanda
ID: 10103332
Course taken in Summer2022:
CSE111
CSE260
ENG101
GPA: 3.8000000000000003