In [ ]:
class Test3:
    def __init__(self):
        self.sum, self.y = 0, 0
    def methodA(self):
        x, y = 2, 3
        msg = [0]
        msg[0] = 3
        y = self.y + msg[0]
        self.methodB(msg, msg[0])
        x = self.y + msg[0]
        self.sum = x + y + msg[0]
        print(x, y, self.sum)
    def methodB(self, mg2, mg1):
        x = 0
        self.y = self.y + mg2[0]
        x = x + 33 + mg1
        self.sum = self.sum + x + self.y
        mg2[0] = self.y + mg1
        mg1 = mg1 + x + 2
        print(x, self.y, self.sum)

t3 = Test3()
t3.methodA()
t3.methodA()
t3.methodA()
t3.methodA()

36 3 39
9 3 18
36 6 60
15 6 30
36 9 75
21 9 42
36 12 90
27 12 54

In [ ]:
class Patient:
  def __init__(self, name, age, weight, height):
    self.name = name
    self.age = age
    self.weight = weight
    self.height = height
    self.bmi = weight/(height/100)**2
  def printDetails(self):
    print(f"Name: {self.name}\nAge: {self.age}\nWeight: {self.weight}\nHeight: {self.height}\nBMI: {self.bmi}")



p1 = Patient("A", 55, 63.0, 158.0)
p1.printDetails()
print("====================")
p2 = Patient("B", 53, 61.0, 149.0)
p2.printDetails()

Name: A
Age: 55
Weight: 63.0
Height: 158.0
BMI: 25.236340330075304
====================
Name: B
Age: 53
Weight: 61.0
Height: 149.0
BMI: 27.476239809017613

In [ ]:
class Batsman:
  def __init__(self, *args):
    if len(args) == 2:
      self.name = "New Batsman"
      self.runs = args[0]
      self.balls = args[1]
    elif len(args) == 3:
      self.name = args[0]
      self.runs = args[1]
      self.balls = args[2]
  def battingStrikeRate(self):
    self.strikerate = self.runs / self.balls *100
    return self.strikerate
  def setName(self, name):
    self.name = name

  def printCareerStatistics(self):
    print(f"Name: {self.name}\nRuns Scored: {self.runs}, Balls Faced: {self.balls}")


b1 = Batsman(6101, 7380)
b1.printCareerStatistics()
print("============================")
b2 = Batsman("Liton Das", 678, 773)
b2.printCareerStatistics()
print("----------------------------")
print(b2.battingStrikeRate())
print("============================")
b1.setName("Shakib Al Hasan")
b1.printCareerStatistics()
print("----------------------------")
print(b1.battingStrikeRate())

Name: New Batsman
Runs Scored: 6101, Balls Faced: 7380
============================
Name: Liton Das
Runs Scored: 678, Balls Faced: 773
----------------------------
87.71021992238033
============================
Name: Shakib Al Hasan
Runs Scored: 6101, Balls Faced: 7380
----------------------------
82.66937669376694

In [ ]:
class Author:
  def __init__(self, name = "Default", *args):
    self.name = name
    self.args = args
  def addBooks(self, *args):
     self.args = args
  def printDetails(self):
     print("Author Name:",self.name)
     print("List of Books:")
     print(*self.args,sep='\n')
  def changeName(self, name2):
    self.name = name2


auth1 = Author('Humayun Ahmed')
auth1.addBooks('Deyal', 'Megher Opor Bari')
auth1.printDetails()
print("===================")
auth2 = Author()
print(auth2.name)
auth2.changeName('Mario Puzo')
auth2.addBooks('The Godfather', 'Omerta', 'The Sicilian')
print("===================")
auth2.printDetails()
print("===================")
auth3 = Author('Paolo Coelho', 'The Alchemist', 'The Fifth Mountain')
auth3.printDetails()

Author Name: Humayun Ahmed
List of Books:
Deyal
Megher Opor Bari
===================
Default
===================
Author Name: Mario Puzo
List of Books:
The Godfather
Omerta
The Sicilian
===================
Author Name: Paolo Coelho
List of Books:
The Alchemist
The Fifth Mountain

In [ ]:
class TaxiLagbe:

taxi1 = TaxiLagbe('1010-01', 'Dhaka')
print('-------------------------------')
taxi1.addPassenger('Walker_100', 'Wood_200')
taxi1.addPassenger('Matt_100')
taxi1.addPassenger('Wilson_105')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi1.addPassenger('Karen_200')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi2 = TaxiLagbe('1010-02', 'Khulna')
taxi2.addPassenger('Ronald_115')
taxi2.addPassenger('Parker_215')
print('-------------------------------')
taxi2.printDetails()

IndentationError: ignored

In [ ]:
class Batsman:
  def __init__(self, *runball):
    self.name = "New Batsman"
    if len(runball) == 2:
      self.run = runball[0]
      self.ball = runball[1]
    elif len(runball) == 3:
      self.name = runball[0]
      self.run = runball[1]
      self.ball = runball[2]
    

  def printCareerStatistics(self):
    print(self.name)
    print(self.run, self.ball)
  def battingStrikeRate(self):
    self.sr = self.run /self.ball *100
    return self.sr
  def setName(self,newname):
    self.name = newname
   
    


b1 = Batsman(6101, 7380)
b1.printCareerStatistics()
print("============================")
b2 = Batsman("Liton Das", 678, 773)
b2.printCareerStatistics()
print("----------------------------")
print(b2.battingStrikeRate())
print("============================")
b1.setName("Shakib Al Hasan")
b1.printCareerStatistics()
print("----------------------------")
print(b1.battingStrikeRate())

New Batsman
6101 7380
============================
Liton Das
678 773
----------------------------
87.71021992238033
============================
Shakib Al Hasan
6101 7380
----------------------------
82.66937669376694

In [ ]:
class QuizA:
   def  __init__(self, z = None):
        self.x = 10
        self.y = 3
        self.sum = 4
 
   def methodA(self, x):
       self.y = x + self.sum
       self.sum = x + self.y
       print(self.x, self.y, self.sum)
       temp = [self.x]
       self.x = self.methodB(temp) + 2
       print(self.x, self.y, self.sum+temp[0])
 
   def methodB(self, a):
       y = 5
       self.sum += self.x + a[0]
       a[0] = a[0] + self.y - self.sum
       print(self.x, y, self.sum)
       return a[0]+5
q1 = QuizA()
q1.methodA(5)
q2 = QuizA("Hi")

10 9 14
10 5 34
-8 9 19

In [ ]:
class Player:
  def __init__(self,info,*sal):
    self.info = info
    self.sal = sal
    print("Player created successfully.")
  def signAdvertisement(self, brand= None):
    if brand == "Nike":
      self.sal += 200
      return f"Hooray! Salary updated for {self.list1[0]}."
    elif brand == "Adidas":
      self.sal += 100    
      return f"Hooray! Salary updated for {self.list1[0]}."
    elif brand == None:
      self.sal = self.sal

  def setSkill(self, *skills):
    self.dict1 = {}
    if len(skills) == 3:
      self.dict1[1] = skills[0]
      self.dict1[2] = skills[1]
      self.dict1[3] = skills[2]
    elif len(skills) == 2:
      self.dict1[1] = skills[0]
      self.dict1[2] = skills[1]
    elif len(skills) == 1:
      self.dict1[1] = skills[0]
  def playerInfo(self):
    list1 = self.info.split(",") 
    print(f"Name: {list1[0]}\nClub: {list1[1]}\nCountry: {list1[2]}")
    if self.sal == 0:
      print("Salary: Information not found")
    else:
      print(f"Salary: {self.sal}")
    print(f"Skills: {self.dict1}")
  def setSalary(self, newsal):
    self.sal = newsal


messi = Player("Messi,PSG,Argentina",60000)
print(messi.signAdvertisement("Nike"))
messi.setSkill("Dribble","Body Faint","Shooting")
print("1====================")
messi.playerInfo()
print("2====================")
neymar = Player("Neymar,PSG,Brazil",50000)
print("3====================")
neymar.signAdvertisement("Adidas")
neymar.setSkill("Neymar turn", "Rollover")
neymar.playerInfo()
print("4====================")
haaland = Player("Haaland,ManCity,Norway")
haaland.setSkill("Acrobatic moves")
haaland.playerInfo()
print("5====================")
haaland.setSalary(40000)
print("6====================")
haaland.playerInfo()

Player created successfully.
Hooray! Salary updated for Messi.
1====================
Name: Messi
Club: PSG
Country: Argentina
Salary: (60000,)
Skills: {1: 'Dribble', 2: 'Body Faint', 3: 'Shooting'}
2====================
Player created successfully.
3====================
Name: Neymar
Club: PSG
Country: Brazil
Salary: (50000,)
Skills: {1: 'Neymar turn', 2: 'Rollover'}
4====================
Player created successfully.
Name: Haaland
Club: ManCity
Country: Norway
Salary: ()
Skills: {1: 'Acrobatic moves'}
5====================
6====================
Name: Haaland
Club: ManCity
Country: Norway
Salary: 40000
Skills: {1: 'Acrobatic moves'}

In [3]:
class Player:
  def __init__(self,info,sal="Information not found"):
    self.info_list = info.split(",")
    if len(self.info_list)==1:
      self.name=self.info_list[0]
    if len(self.info_list)==2:
      self.name=self.info_list[0]
      self.club=self.info_list[1]
    if len(self.info_list)==3:
      self.name=self.info_list[0]
      self.club=self.info_list[1]
      self.country=self.info_list[2]
    self.sal = sal
    print("Player created successfully.")
  def signAdvertisement(self, brand=None):
    if brand == 'Nike':
      self.sal = self.sal + 200
      return f"Hooray! Salary updated for {self.name}."
    elif brand == 'Adidas':
      self.sal = self.sal + 100
      return f"Hooray! Salary updated for {self.name}."
    elif brand == None:
      self.sal = self.sal
  def setSkill(self, *skills):
    self.skills = skills
    self.dict1 = {}
    if len(skills) == 3:
      self.dict1[1] = skills[0]
      self.dict1[2] = skills[1]
      self.dict1[3] = skills[2]
    elif len(skills) == 2:
      self.dict1[1] = skills[0]
      self.dict1[2] = skills[1]
    elif len(skills) == 1:
      self.dict1[1] = skills[0]
  def playerInfo(self):
    print(f"Name: {self.name}\nClub: {self.club}\nCountry: {self.country}\nSalary: {self.sal}\nSkills: {self.dict1}")
  def setSalary(self, newsal):
    self.sal = newsal
messi = Player("Messi,PSG,Argentina",60000)
print(messi.signAdvertisement("Nike"))
messi.setSkill("Dribble","Body Faint","Shooting")
print("1====================")
messi.playerInfo()
print("2====================")
neymar = Player("Neymar,PSG,Brazil",50000)
print("3====================")
neymar.signAdvertisement("Adidas")
neymar.setSkill("Neymar turn", "Rollover")
neymar.playerInfo()
print("4====================")
haaland = Player("Haaland,ManCity,Norway")
haaland.setSkill("Acrobatic moves")
haaland.playerInfo()
print("5====================")
haaland.setSalary(40000)
print("6====================")
haaland.playerInfo()

Player created successfully.
Hooray! Salary updated for Messi.
1====================
Name: Messi
Club: PSG
Country: Argentina
Salary: 60200
Skills: {1: 'Dribble', 2: 'Body Faint', 3: 'Shooting'}
2====================
Player created successfully.
3====================
Name: Neymar
Club: PSG
Country: Brazil
Salary: 50100
Skills: {1: 'Neymar turn', 2: 'Rollover'}
4====================
Player created successfully.
Name: Haaland
Club: ManCity
Country: Norway
Salary: Information not found
Skills: {1: 'Acrobatic moves'}
5====================
6====================
Name: Haaland
Club: ManCity
Country: Norway
Salary: 40000
Skills: {1: 'Acrobatic moves'}

In [11]:
str1 = "A1b dC @   3 $"
str1 = str1.replace(" ", "")
var1 = ""
var2 = ""
var3 = ""
var4 = ""
new_word = ""
for item in str1:
  if ord('A')<= ord(item)<= ord("Z"):
    var1 += item
  elif ord('a')<= ord(item)<= ord("z"):
    var2 += item
  elif ord('1')<= ord(item)<= ord("9"):
    var3 += item
  else:
    var4 += item
print("Upper-Case:", var1)
print("Lower-Case:", var2)
print("Digits:", var3)
print("Special:", var4)
new_word += var1[0]+var2[0]+var3[0]+var4[0]+ var1[1]+var2[1]+var3[1]+var4[1]
print(new_word)

Upper-Case: AC
Lower-Case: bd
Digits: 13
Special: @$
Ab1@Cd3$